services:
  ctf_env:
    build: .
    container_name: ctf_env
    volumes:
      - ~/Desktop/CTF_Archive:/usr/src/app/ctf
      - ~/Downloads:/usr/src/app/downloads
    # ports:
    #   - "8080:80" # Port for web challenges if needed
    command: tail -f /dev/null